SUPABASE_URL = "https://mzldxmdrfrtqxpnzxiwe.supabase.co"
SUPABASE_KEY = "sb_publishable_tH1dp-Y_Aqn7Dv7-O0xlUw_BIvC9egc"
GITHUB_REPO = "https://github.com/EEEEEEETETETETASD/projectzozfil"
OWNER_USERNAME = "Owner"
OWNER_PASSWORD = "$6vC9vp4d$"